ClientesWebService/Controllers/HomeController.cs
using ClientesWebService.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ClientesWebService.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClientesWebService/Controllers/LibrosPorUsuarioController.cs
using Books.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Books.Controllers
{
    public class LibrosPorUsuarioController : Controller
    {

        private readonly HttpClient _httpClient;
        private readonly string _apiUrl;

        public LibrosPorUsuarioController(HttpClient httpClient, IConfiguration configuration)
        {

            _httpClient = httpClient;
            _apiUrl = configuration.GetValue<string>("APIUrl");
        }
        // GET: LibrosPorUsuario
        public async Task<ActionResult> librosUsuarios()
        {

            var response = await _httpClient.GetAsync($"{_apiUrl}BookService/GetListBooksUsers");
            response.EnsureSuccessStatusCode();
            var responseBody = await response.Content.ReadAsStringAsync();
            var listaLibros = JsonConvert.DeserializeObject<Dictionary<string, ListaLibrosUsuarios>>(responseBody);


            return View(listaLibros);
        }

        // GET: LibrosPorUsuario/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LibrosPorUsuario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LibrosPorUsuario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LibrosPorUsuario/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LibrosPorUsuario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LibrosPorUsuario/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LibrosPorUsuario/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ClientesWebService/Controllers/ReporteStockController.cs
using System.IO;
using System.Reflection;
using AspNetCore.Reporting;
using Microsoft.AspNetCore.Mvc;

namespace Books.Controllers
{
    public class ReportStockController : Controller
    {
        public ActionResult ReporteStock(string reportName, string format = "PDF")
        {
            var assembly = Assembly.GetExecutingAssembly();
            var resourceName = $"Books.Resources.{reportName}.rdl";

           


            using var stream = assembly.GetManifestResourceStream(resourceName);
            if (stream == null)
            {
                return NotFound("Informe no encontrado");
            }

          
            var tempFilePath = Path.GetTempFileName();
            using (var fileStream = new FileStream(tempFilePath, FileMode.Create, FileAccess.Write))
            {
                stream.CopyTo(fileStream);
            }

       
            var localReport = new LocalReport(tempFilePath);



            var result = localReport.Execute(RenderType.Pdf);
            var base64string = Convert.ToBase64String(result.MainStream.ToArray());
            ViewBag.ReportBase64 = base64string;

            return View();
        }
    }
}

ClientesWebService/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Clientes y productos";
}

<div class="container">
    <div class="text-center">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Customer", "Customer")">Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Book", "Book")">Libros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Ingreso", "Ingreso")">Ingreso de productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Salidas", "Salidas")">Salida de productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("CustomerList", "CustomerList")">Lista de clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("librosUsuarios", "LibrosPorUsuario")">Lista de libros por clientes</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("ReporteStock", "ReportStock", new { reportName = "ReportLibros" })">Reporte de stock de libros</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("ConsultaSalidas", "ConsultaSalidas", new { reportName = "ReporteRetiros" })">Reporte de Salidas</a>
                    </li>

                </ul>
            </div>
        </nav>
    </div>
</div>