ClientesWebService/Controllers/ConsultaSalidasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Books.Controllers
{
    public class ConsultaSalidasController : Controller
    {
        // GET: ConsultaSalidasController
        public ActionResult ConsultaSalidas()
        {
            return View();
        }

        // GET: ConsultaSalidasController/Details
        public ActionResult ReporteSalida(string fechaInicio, string fechaFinal)
        {
                string nombreReporte = "ReportLibro";
                return RedirectToAction("ReporteSalidas", "ReporteSalidas", new { reportName = nombreReporte,FechaInicio=fechaInicio,FechaFinal=fechaFinal });
        }


    }
}

ClientesWebService/Views/ConsultaSalidas/ConsultaSalidas.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <h3>Reporte de salidas</h3>

    @using (Html.BeginForm("ReporteSalida", "ConsultaSalidas", FormMethod.Post, new { id = "FormCustomerBook" }))
    {

        <div class="mb-3">
            <label for="ClientCode" class="form-label">Fecha inicio</label>
            <input type="date" required class="form-control" id="FechaInicio" name="FechaInicio">
            <label for="ClientCode" class="form-label">Fecha final</label>
            <input type="date" required class="form-control" id="FechaFinal" name="FechaFinal">
            <br/>
            <input class="btn-primary" value="Realizar consulta" type="submit"/>
            </div>
    }
}